line-length = 100
target-version = "py311"

[lint]
select = ["E","F","I","N","UP","B","ASYNC","S"]
ignore = ["E203"]

[lint.per-file-ignores]
"tests/**/*" = ["S101","S113","E501"]

[lint.isort]
known-first-party = ["apps","integrations"]
